### PR TITLE
Support large cluster sizes and correct position of backup volume header

### PR DESCRIPTION
**Pull request by jimuk**
This change supports the larger cluster sizes introduced in recent Windows 10 and removes an assumption about the sector size.
It also corrects the location of the backup volume header which typically appears in the sector immediately after the volume size (number of sectors) provided in the volume header. 

If this quick patch is acceptable, a fuller solution could:

1. Detect if the data source (volume) has sufficient sectors to match the volume header e.g. All addressable clusters are present
2. Accept the case where the backup volume header is missing (because some image tools don't include this sector)

### CODE REVIEW

**Comment by joachimmetz** [comment]
@jimuk thx for the proposed changes but do you have test data, method or debug output that you can share that indicates the use of large cluster sizes by the format?

**Comment by jimuk** [comment]
> @jimuk thx for the proposed changes but do you have test data, method or debug output that you can share that indicates the use of large cluster sizes by the format?

This large cluster size support is essentially the same as that already in libfsntfs. 

Going further, I would like to make the check for the backup volume header optional because I'm aware that some image tools omit this from the end of the image. It's nice if it's there, but things don't need to break if it isn't.

**Comment by joachimmetz** [comment]
> This large cluster size support is essentially the same as that already in libfsntfs.

I see, I'll change https://github.com/dfirlabs/vss-specimens then to generate some test files.

> Going further, I would like to make the check for the backup volume header optional because I'm aware that some image tools omit this from the end of the image. It's nice if it's there, but things don't need to break if it isn't

If I recall correctly, the reason for adding this is to ensure the full volume is available and no input data is missing.

**Comment by jimuk** [comment]
> If I recall correctly, the reason for adding this is to ensure the full volume is available and no input data is missing.

I would suggest the libfsntfs, libvshadow etc libraries gracefully tolerate images which are no longer than the last addressable cluster. This is because some lame imaging tools (mentioning no names, but one starts with an "X") don't image past this point. This means the image is missing any slack space present after the last addressable cluster and the backup volume header. 

NB: Such slack space can happen if the parent partition is not a multiple of the cluster size in length. This leaves an "incomplete" cluster after the last addressable one.

**Comment by joachimmetz** [comment]
Ack, I'll have a look into this when time permits. Some form of size sanity check is likely still needed since I've seen people trying to feed libvshadow significant incomplete data (not only the last cluster) before and then wondering why the library errors.

**Comment by joachimmetz** [comment]
So the reason for the back NTFS header check is to ensure the full volume is present. So that the volume size in the catalog matches that indicated by NTFS volume/file system.

One alternative (and more general purpose) approach to this might be to create a kind of "overlay layer" that allows to fake the missing NTFS backup volume header. This approach would be tool/library independent and also could facilitate in supporting needs like https://github.com/libyal/libvshadow/pull/18

**Comment by jimuk** [comment]
Would it be sufficient to check the underlying libbfio size and proceed if enough data was present to match the VBR? (In other words, ignore the backup VBR).

**Comment by joachimmetz** [comment]
> Would it be sufficient to check the underlying libbfio size and proceed if enough data was present to match the VBR? (In other words, ignore the backup VBR).

That would not be sufficient since the VSS (volsnal) layer will do bounds checks and determine that data is missing. A volume snapshot can contain the copy of a previous version of the backup volume header. To properly compensate for that, the missing blocks would need to be emulated. And this would need to be replicated by any other library/tool that needs to compensate for the same corruption scenario.

**Comment by jimuk** [comment]
Ok. The situation is clearly much more complicated than I anticipated. I am sorry if I have just created a lot of work. Maybe the scenario isn't very common? The code I suggested may be sufficient for now because it fixes the large cluster size issue and corrects the calculation for the volume size?

**Comment by joachimmetz** [comment]
> Maybe the scenario isn't very common? 

I've seen it in the past, mainly for live captured images of Window volumes. If you have test images or know which tools are creating such images feel free to pass me an email. 

I've created https://github.com/log2timeline/dfvfs/issues/514 to think of a general solution for such corrupted/truncated images. Seeing #18 and the missing backup volume header scenario there is a need to "manipulate" corrupt/truncated input data.

> The code I suggested may be sufficient for now because it fixes the large cluster size issue and corrects the calculation for the volume size?

I'll likely incorporate similar changes into a single commit including some more NTFS volume header sanity checkes. Once the test files are complete and changes tested I'll update this PR with the commit. Thx for raising the issue.

**Comment by joachimmetz** [comment]
I've incorporated similar changes as this PR into https://github.com/libyal/libvshadow/commit/4c3dbad075dbedb23a9a4085f1de1613fae14f79. For me these work on the tests images generated by https://github.com/dfirlabs/vss-specimens and one 4k sector image that still needs to be captured in a script.

Let me know if that does the trick for you.

**Comment by jimuk** [comment]
> I've incorporated similar changes as this PR into [4c3dbad](https://github.com/libyal/libvshadow/commit/4c3dbad075dbedb23a9a4085f1de1613fae14f79). For me these work on the tests images generated by https://github.com/dfirlabs/vss-specimens and one 4k sector image that still needs to be captured in a script.
> 
> Let me know if that does the trick for you.

Thank you. The updated version works fine.

**Comment by joachimmetz** [comment]
a way to work around truncated Windows volume images https://github.com/libyal/libbfoverlay/wiki/Examples#correcting-truncated-windows-live-volume-images

**Comment by jimuk** [comment]
Thank you.

It is frustrating that some image tools don't include the backup boot sector. However, I would argue that Libvshadow treat this is optional provided the number of sectors specified in the NTFS VBR is present in the underlying data. In other words, it should be fine to go with the primary VBR if it is consistent with the data.

**Comment by joachimmetz** [comment]
As I said before. The presence of the backup volume header is **not** optional for VSS. A VSS can describe a replacement for the backup volume header. Hence it is part of the required data thus such a volume image without it is corrupted. I would strongly encourage to get the image tool fixed since it is missing data (or stop using it).

**Comment by jimuk** [comment]
> A volume snapshot can contain the copy of a previous version of the backup volume header. To properly compensate for that, the missing blocks would need to be emulated.

Surely if the volume had substantially changed (e.g. different number of sectors) it would be a different volume and any previous VSS would be irrelevant?

Please, what circumstances do you think the backup VBR could differ from the primary VBR but still describe substantially the same file system?

**Comment by joachimmetz** [comment]
@jimuk I don't have the time to argue with you over the relevance of the NTFS backup volume header.

**Pull request closed without merging**
